apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: searchpilot
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "searchpilot"
  MYSQL_USER: "searchuser"
  MYSQL_PASSWORD: "searchpass"

